export const commentsList = [
  {
    commentId: 1,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'This is just amazing! 🔥🔥',
    time: '2m',
    isLiked: true,
  },
  {
    commentId: 2,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    comment: 'Love the vibes in this shot! 🌄',
    time: '5m',
    isLiked: false,
  },
  {
    commentId: 3,
    username: 'Vamshi4102',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'So inspiring! Keep going! 💯',
    time: '15m',
    isLiked: true,
  },
  {
    commentId: 4,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Can’t stop watching this. So good!',
    time: '30m',
    isLiked: false,
  },
  {
    commentId: 5,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    comment: 'Legendary post! 🏆🙌',
    time: '1h',
    isLiked: true,
  },
  {
    commentId: 6,
    username: 'Vamshi4102',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Wow, this is art! 😍👏',
    time: '2h',
    isLiked: false,
  },
  {
    commentId: 7,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Feeling motivated just looking at this!',
    time: '3h',
    isLiked: true,
  },
  {
    commentId: 8,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    comment: 'Amazing shot, bro! 💪🏼🔥',
    time: '5h',
    isLiked: true,
  },
  {
    commentId: 9,
    username: 'Vamshi4102',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Goals! 🤩🌟',
    time: '7h',
    isLiked: false,
  },
  {
    commentId: 10,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Incredible view! 🏞️',
    time: '10h',
    isLiked: true,
  },
  {
    commentId: 11,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    comment: 'You’re on fire! 🔥🔥🔥',
    time: '12h',
    isLiked: false,
  },
  {
    commentId: 12,
    username: 'Vamshi4102',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Can’t wait for more like this!',
    time: '15h',
    isLiked: true,
  },
  {
    commentId: 13,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'This is everything! 🙌✨',
    time: '1d',
    isLiked: false,
  },
  {
    commentId: 14,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    comment: 'Mind-blowing moment captured! 😲',
    time: '1d',
    isLiked: true,
  },
  {
    commentId: 15,
    username: 'Vamshi4102',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'A whole vibe! 🎶🕶️',
    time: '2d',
    isLiked: false,
  },
  {
    commentId: 16,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Unreal! 📸👏',
    time: '3d',
    isLiked: true,
  },
  {
    commentId: 17,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    comment: 'Total masterpiece! 🖼️',
    time: '3d',
    isLiked: false,
  },
  {
    commentId: 18,
    username: 'Vamshi4102',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Loving the aesthetic here 💖',
    time: '4d',
    isLiked: true,
  },
  {
    commentId: 19,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    comment: 'Epic moment captured! 📷',
    time: '5d',
    isLiked: true,
  },
  {
    commentId: 20,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    comment: 'Too good to be true! 😍',
    time: '6d',
    isLiked: false,
  },
];

export const shareList = [
  {
    userId: 1,
    username: 'Vamshikrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    lastSeen: 2,
    isActive: true,
  },
  {
    userId: 2,
    username: 'hanuman',
    profile_picture: 'https://one-link.in/youtube/profiles/hanuman.png',
    lastSeen: 5,
    isActive: true,
  },
  {
    userId: 3,
    username: 'Vamshi4102',
    profile_picture: 'https://one-link.in/youtube/profiles/vamshi4102.png',
    lastSeen: 15,
    isActive: false,
  },
  {
    userId: 4,
    username: 'Ramakrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/user-1.png',
    lastSeen: 60,
    isActive: false,
  },
  {
    userId: 5,
    username: 'SaiKrishna',
    profile_picture: 'https://one-link.in/youtube/profiles/user-2.png',
    lastSeen: 120,
    isActive: false,
  },
  {
    userId: 6,
    username: 'Suresh',
    profile_picture: 'https://one-link.in/youtube/profiles/user-3.png',
    lastSeen: 5,
    isActive: false,
  },
  {
    userId: 7,
    username: 'Shiva',
    profile_picture: 'https://one-link.in/youtube/profiles/user-1.png',
    lastSeen: 6,
    isActive: true,
  },
  {
    userId: 8,
    username: 'Ganesh',
    profile_picture: 'https://one-link.in/youtube/profiles/user-2.png',
    lastSeen: 8,
    isActive: false,
  },
  {
    userId: 9,
    username: 'Lakshmi',
    profile_picture: 'https://one-link.in/youtube/profiles/user-3.png',
    lastSeen: 2880,
    isActive: false,
  },
  {
    userId: 10,
    username: 'Radha',
    profile_picture: 'https://one-link.in/youtube/profiles/user-1.png',
    lastSeen: 4320,
    isActive: false,
  },
];
